### ISSUE TITLE
`LinFit` import fails on `snowline` import

### ISSUE THREAD

**Issue by granttremblay** [CullanHowlett/HyperFit#3]
Thank you, Cullan, for this phenomenally useful package! 

I'm just raising a potential issue here, which I'm still investigating: 

After installing `hyperfit` via `pip install hyperfit` on a clean Anaconda v. `2021.05` environment with python `3.8.8`, I get the following failure when attempting to import `hyperfit.linfit.LinFit`. See below. It looks like it fails on the import of Johannes Buchner's excellent `snowline` package. I assume the issues lies with a version collision. Still investigating. 

<img width="1283" alt="Screen Shot 2022-02-13 at 10 11 26 PM" src="https://user-images.githubusercontent.com/2238418/153794269-95b72758-3283-4afd-a6dc-61d73e15905c.png">

**Comment by granttremblay** [comment]
(I've created an issue at the `snowline` page, by the way - it's really more of an issue on that end...

**Comment by granttremblay** [comment]
*whoops*! Really sorry - my conda environment was borked. I've fixed it!

**Comment by tamarastro** [comment]
I had the same issue.  Updating pip and then reinstalling hyperfit (and dependencies) fixed it. 
```
python -m pip install --upgrade pip
pip install --upgrade --force-reinstall hyperfit
```
